trigger:
  branches:
    include:
      - master
  tags:
    include:
      - '*'

schedules:
- cron: '0 3 * * 6'
  displayName: "Weekly scheduled build"
  branches:
    include:
      - 'master'
  always: true

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    mkdir -p /tmp/target/EFI
    cp -r BOOT OC /tmp/target/EFI
    cd /tmp/target
    zip -r /tmp/release.zip .
  displayName: 'Prepare EFI'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_nickw444'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    assets: /tmp/release.zip'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'